# Configuration de Bandit pour l'analyse de sécurité
# Exécution : bandit -c .bandit.yml -r src/

targets:
  - src/

exclude_dirs:
  - "*.venv"
  - "*/tests"
  - "*/docs"
  - "*/examples"
  - "*/build"
  - "*/.git"
  - "*/__pycache__"
  - "*/.pytest_cache"

skips:
  # Désactive les avertissements courants non pertinents
  - B101  # assert_used
  - B104  # hardcoded_bind_all_interfaces
  - B107  # hardcoded_password_default
  - B112  # try_except_continue
  - B311  # blacklist
  - B405  # import_xml_etree
  - B406  # import_xml_etree_cElementTree
  - B410  # import_lxml
  - B603  # subprocess_without_shell_equals_true
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions

# Active les tests de sécurité importants
tests:
  - B102  # exec_used
  - B103  # set_bad_file_permissions
  - B105  # hardcoded_password_string
  - B106  # hardcoded_password_funcarg
  - B108  # hardcoded_tmp_directory
  - B110  # try_except_pass
  - B201  # flask_debug_true
  - B301  # pickle
  - B302  # marshal
  - B303  # md5
  - B304  # ciphers
  - B305  # cipher_modes
  - B306  # mktemp_qs
  - B307  # eval
  - B308  # mark_safe
  - B309  # httpsconnection
  - B310  # urllib_urlopen
  - B312  # telnetlib
  - B313  # xml_bad_cElementTree
  - B314  # ftplib
  - B315  # httpoxy
  - B316  # flask_mark_safe
  - B317  # cgi_httpd
  - B318  # jinja2_autoescape
  - B319  # mako_templates
  - B320  # yaml_load
  - B321  # flask_caching
  - B322  # input
  - B323  # unverified_context
  - B324  # hashlib_insecure_functions
  - B325  # tempfile_mktemp
  - B401  # import_subprocess
  - B402  # import_ftplib
  - B403  # import_pickle
  - B404  # import_subprocess
  - B405  # import_xml_etree
  - B406  # import_xml_etree_cElementTree
  - B407  # import_xml_sax
  - B408  # import_xml_expat
  - B409  # import_xml_minidom
  - B410  # import_lxml
  - B411  # import_xmlrpclib
  - B412  # import_httpoxy
  - B413  # import_pycrypto
  - B414  # import_urllib3
  - B415  # import_urllib
  - B416  # import_urllib2
  - B501  # request_without_timeout
  - B502  # ssl_with_bad_version
  - B503  # ssl_with_bad_defaults
  - B504  # ssl_with_no_version
  - B505  # ssl_with_bad_cert
  - B506  # yaml_load
  - B507  # ssh_no_host_key_verification
  - B508  # snmp_insecure_version
  - B509  # snmp_weak_cryptography
  - B510  # snmp_v1_v2c
  - B601  # paramiko_calls
  - B602  # subprocess_popen_with_shell_equals_true
  - B603  # subprocess_popen_without_shell_equals_true
  - B604  # any_other_function_with_shell_equals_true
  - B605  # start_process_with_a_shell
  - B606  # start_process_with_no_shell
  - B607  # start_process_with_partial_path
  - B608  # hardcoded_sql_expressions
  - B609  # linux_commands_wildcard_injection
  - B610  # django_extra_used
  - B611  # django_raw_sql
  - B612  # logging_config_insecure_listen
  - B613  # expression_not_assigned
  - B614  # django_mark_safe
  - B615  # django_csrf_cookie_httponly_false
  - B616  # django_csrf_cookie_secure_false
  - B617  # django_csrf_cookie_samesite_none
  - B618  # django_csrf_cookie_not_httponly
  - B619  # django_csrf_cookie_not_secure
  - B620  # django_csrf_cookie_samesite_lax
  - B621  # django_csrf_cookie_samesite_strict
  - B622  # django_csrf_cookie_samesite_unsafe
  - B623  # django_csrf_cookie_samesite_invalid
  - B624  # django_csrf_cookie_samesite_missing
  - B625  # django_csrf_cookie_httponly_true
  - B626  # django_csrf_cookie_secure_true
  - B627  # django_csrf_cookie_samesite_none_plus_secure
  - B628  # django_csrf_cookie_samesite_lax_plus_secure
  - B629  # django_csrf_cookie_samesite_strict_plus_secure
  - B630  # django_csrf_cookie_samesite_unsafe_plus_secure
  - B631  # django_csrf_cookie_samesite_invalid_plus_secure
  - B632  # django_csrf_cookie_samesite_missing_plus_secure
  - B633  # django_csrf_cookie_httponly_false_plus_secure
  - B634  # django_csrf_cookie_secure_false_plus_secure
  - B635  # django_csrf_cookie_samesite_none_plus_not_secure
  - B636  # django_csrf_cookie_samesite_lax_plus_not_secure
  - B637  # django_csrf_cookie_samesite_strict_plus_not_secure
  - B638  # django_csrf_cookie_samesite_unsafe_plus_not_secure
  - B639  # django_csrf_cookie_samesite_invalid_plus_not_secure
  - B640  # django_csrf_cookie_samesite_missing_plus_not_secure
  - B641  # django_csrf_cookie_httponly_true_plus_not_secure
  - B642  # django_csrf_cookie_secure_true_plus_not_secure