# Configuration pour yamllint
# Documentation : https://yamllint.readthedocs.io/

extends: default

rules:
  # Formatage
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 3
    max-start: 0
    max-end: 1
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: {}
  trailing-spaces: enable

  # Structure
  document-end: disable
  document-start: disable
  empty-values: {}
  float-values: {}
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values:
    required-encoding: dec
  quoted-strings:
    required: only-when-needed
    extra-required: [']
    extra-allowed: []
  trailing-spaces: {}
  truthy: {}

  # Style
  braces:
    level: error
    max-spaces-inside: 1
    min-spaces-inside: 0
    min-spaces-inside-empty: -1
  brackets:
    level: error
    max-spaces-inside: 1
    min-spaces-inside: 0
    min-spaces-inside-empty: -1
  colons:
    level: error
    max-spaces-after: 3
    max-spaces-before: 0
  commas:
    level: error
    max-spaces-after: 1
    max-spaces-before: 0
  comments-indentation: {}
  empty-lines:
    level: warning
    max: 2
    max-start: 0
    max-end: 1
  hyphens:
    level: error
  indentation:
    level: error
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
  key-duplicates:
    level: error
  key-ordering: {}
  line-length:
    level: warning
    max: 88
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  new-line-at-end-of-file:
    level: error
  new-lines:
    level: error
    type: unix
  trailing-spaces:
    level: error

# Exceptions pour les fichiers spécifiques
exclude: |
  (?x)
  # Exclure les fichiers de verrouillage
  ^(\.venv|venv|env|.tox|.pytest_cache|.mypy_cache|.hypothesis|.eggs|build|dist|__pycache__|.git|.github|.vscode|.idea|
  # Fichiers spécifiques à exclure
  ^\.gitignore$
  ^\.pre-commit-config\.yaml$
  ^\.markdownlint\.json$
  ^\.yamllint\.yml$
  ^pytest\.ini$
  ^mypy\.ini$
  # Dossiers à exclure
  |docs/|tests/|examples/|notebooks/|scripts/|data/|models/|logs/|reports/|coverage/|htmlcov/|.pytest_cache/|.mypy_cache/|.hypothesis/|.eggs/|build/|dist/|__pycache__/|.git/|.github/|.vscode/|.idea/)

# Configuration spécifique pour les fichiers YAML
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
  - '.travis.yml'
  - '.github/workflows/*.yml'
  - '**/templates/*.yaml'
  - '**/templates/*.yml'
