name: Unit Tests (Timeout)

on:
  push:
  pull_request:

jobs:
  unit-tests-timeout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run targeted unit tests (Timeout & Trainer)
        run: |
          pytest -q tests/unit/utils/test_timeout_manager.py \
                     tests/unit/training/test_trainer_timeout_integration.py \
                     tests/unit/training/test_parallel_trainer_timeout.py \
                     -c /dev/null
